## Numpy

In [14]:
# Numpy
import numpy as np

# define two custom numpy arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

# stack vertically
vertical = np.vstack((a, b))
# stack horizontally
horizontal = np.hstack((a, b))

print(vertical)
print(horizontal)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
# find common elements
common_elements = np.intersect1d(a, b)
print("Common elements:", common_elements)

Common elements: []


In [16]:
# extract elements within a specific range (e.g., between 5 and 10)
filtered_a = a[(a >= 5) & (a <= 10)]
print("Elements in 'a' between 5 and 10:", filtered_a)

Elements in 'a' between 5 and 10: [5]


In [17]:
# filter the rows of iris_2d
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered iris_2d rows:\n", filtered_iris)

Filtered iris_2d rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


## Pandas

From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

    Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

    How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))


In [18]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# filter 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0)
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
display(filtered_df)

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# replace missing values in Min.Price and Max.Price columns with their respective mean
display(df)

Manufacturer    Model     Type  ...  Weight   Origin                Make
0         Acura  Integra    Small  ...  2705.0  non-USA       Acura Integra
1           NaN   Legend  Midsize  ...  3560.0  non-USA        Acura Legend
2          Audi       90  Compact  ...  3375.0  non-USA             Audi 90
3          Audi      100  Midsize  ...  3405.0  non-USA            Audi 100
4           BMW     535i  Midsize  ...  3640.0  non-USA            BMW 535i
..          ...      ...      ...  ...     ...      ...                 ...
88   Volkswagen  Eurovan      Van  ...  3960.0      NaN  Volkswagen Eurovan
89   Volkswagen   Passat  Compact  ...  2985.0  non-USA   Volkswagen Passat
90   Volkswagen  Corrado   Sporty  ...  2810.0  non-USA  Volkswagen Corrado
91        Volvo      240  Compact  ...  2985.0  non-USA           Volvo 240
92          NaN      850  Midsize  ...  3245.0  non-USA           Volvo 850

[93 rows x 27 columns]

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# replace missing values in Min.Price and Max.Price columns with their respective mean
display(df)

Manufacturer    Model     Type  ...  Weight   Origin                Make
0         Acura  Integra    Small  ...  2705.0  non-USA       Acura Integra
1           NaN   Legend  Midsize  ...  3560.0  non-USA        Acura Legend
2          Audi       90  Compact  ...  3375.0  non-USA             Audi 90
3          Audi      100  Midsize  ...  3405.0  non-USA            Audi 100
4           BMW     535i  Midsize  ...  3640.0  non-USA            BMW 535i
..          ...      ...      ...  ...     ...      ...                 ...
88   Volkswagen  Eurovan      Van  ...  3960.0      NaN  Volkswagen Eurovan
89   Volkswagen   Passat  Compact  ...  2985.0  non-USA   Volkswagen Passat
90   Volkswagen  Corrado   Sporty  ...  2810.0  non-USA  Volkswagen Corrado
91        Volvo      240  Compact  ...  2985.0  non-USA           Volvo 240
92          NaN      850  Midsize  ...  3245.0  non-USA           Volvo 850

[93 rows x 27 columns]

In [22]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# replace missing values in Min.Price and Max.Price columns with their respective mean
df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())

display(df.head())

Manufacturer    Model     Type  ...  Weight   Origin           Make
0        Acura  Integra    Small  ...  2705.0  non-USA  Acura Integra
1          NaN   Legend  Midsize  ...  3560.0  non-USA   Acura Legend
2         Audi       90  Compact  ...  3375.0  non-USA        Audi 90
3         Audi      100  Midsize  ...  3405.0  non-USA       Audi 100
4          BMW     535i  Midsize  ...  3640.0  non-USA       BMW 535i

[5 rows x 27 columns]

In [23]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# get the rows of a dataframe with row sum > 100
filtered_df_sum = df[df.sum(axis=1) > 100]
display(filtered_df_sum)

0   1   2   3
1   27  28  39  11
4   25  22  34  24
6   32  39  34  30
8   24  26  28  38
10  28  38  27  38
11  28  32  33  32